# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cis"
BBFILE_PATTERN_meta-cis = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-cis = "8"
LAYERSERIES_COMPAT_meta-cis = "langdale"
LICENSE_PATH += "${LAYERDIR}/licenses"
require cis_extra.conf
